name: Build

on:
  release:
  workflow_dispatch:

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.14
      - run: go version 
      - run: mkdir BUILD
      - run: go build -o mealie-cli
      - uses: actions/upload-artifact@v2
        with: 
          name: mealie-cli
          path: mealie-cli
  